// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHsz0VvKMLnoFDKXecQ2NGvLJd35QtI8',
    appId: '1:521600751887:web:0868ba68530c6ef478067a',
    messagingSenderId: '521600751887',
    projectId: 'news-7e7a2',
    authDomain: 'news-7e7a2.firebaseapp.com',
    storageBucket: 'news-7e7a2.firebasestorage.app',
    measurementId: 'G-P1JCGTGKPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdh7hnWcJkx1WsBVWvD1pv2ldBnVdMF9k',
    appId: '1:521600751887:android:e0e8b02bed5e531178067a',
    messagingSenderId: '521600751887',
    projectId: 'news-7e7a2',
    storageBucket: 'news-7e7a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJgXSeEvIf2bhjuTIRh5qtVLgx4iWB_QE',
    appId: '1:521600751887:ios:cfc130d7be85254278067a',
    messagingSenderId: '521600751887',
    projectId: 'news-7e7a2',
    storageBucket: 'news-7e7a2.firebasestorage.app',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJgXSeEvIf2bhjuTIRh5qtVLgx4iWB_QE',
    appId: '1:521600751887:ios:cfc130d7be85254278067a',
    messagingSenderId: '521600751887',
    projectId: 'news-7e7a2',
    storageBucket: 'news-7e7a2.firebasestorage.app',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtHsz0VvKMLnoFDKXecQ2NGvLJd35QtI8',
    appId: '1:521600751887:web:240beb9d450f662478067a',
    messagingSenderId: '521600751887',
    projectId: 'news-7e7a2',
    authDomain: 'news-7e7a2.firebaseapp.com',
    storageBucket: 'news-7e7a2.firebasestorage.app',
    measurementId: 'G-BN963Y6PNR',
  );
}
